# Site settings
title: my daily grind
email: zigomir@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Things I thought I wanted to share.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.zigomir.com" # the base hostname & protocol for your site
twitter_username: zigomir
github_username:  zigomir

# Build settings
markdown: kramdown
